### ISSUE TITLE
Wisdom teeth update

### ISSUE THREAD

**Issue by john-breton** [RPahlevan/OODesignFinal2021#5]
Hi all,

So I had my wisdom teeth removed this afternoon. Unfortunately one of my arteries was cut so I'm not exactly feeling great (although I'm doing okay health wise). I am still going to finish up the mediator but I probably won't get to it until Sunday. I also don't think I'll be going into work on Monday and potential Tuesday. Didn't know the best way to get this update out to everyone so I thought a GitHub issue was a good idea lol. Just wanted to keep everyone in the loop.

**Comment by RPahlevan** [comment]
Hey John,

I just see your comment and I hope you get better soon.
